# Generated by Django 3.1.1 on 2020-09-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipclass',
            name='crew_requirement',
            field=models.IntegerField(default=0),
        ),
    ]
