# Generated by Django 3.1.1 on 2020-09-05 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew_tracker', '0002_shipclass_crew_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewman',
            name='ship_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crew_tracker.starship'),
        ),
    ]
